apiVersion: 1

datasources:
  - name: KELEDON Jaeger
    uid: keledon-jaeger
    type: jaeger
    access: proxy
    url: http://keledon-jaeger:16686
    isDefault: true
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: ""
      nodeGraph:
        enabled: true
      spanBar:
        type: None
