#!/bin/bash

# KELEDON - Complete Automatic Deployment Script for Google Cloud Run
# This script deploys both backend and frontend services with proper configuration
# 
# Usage: ./deploy-all.sh [PROJECT_ID] [REGION] [DOMAIN]
# Example: ./deploy-all.sh my-project-id us-central1 keledon.com

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_step() {
    echo -e "${BLUE}🔸 $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Default values
PROJECT_ID=${1:-"your-project-id"}
REGION=${2:-"us-central1"}
DOMAIN=${3:-""}

# Service names
CLOUD_SERVICE="keledon-cloud"
LANDING_SERVICE="keledon-landing"

# Supabase configuration (KELEDON specific)
SUPABASE_URL="https://isoyzcvjoevyphnaznkl.supabase.co"
SUPABASE_ANON_KEY="sb_publishable_9sKVxamNyK4CdXM-yH69qg_fEHRvHRa"
SUPABASE_SERVICE_KEY="sb_secret_yqq_tgfKS_2BgKviwVn1lw_W_RbzJVV"

echo -e "${BLUE}"
echo "🚀 KELEDON - Automatic Cloud Run Deployment"
echo "============================================="
echo -e "${NC}"

print_step "Configuration Summary:"
echo "   Project ID: $PROJECT_ID"
echo "   Region: $REGION"
echo "   Domain: $DOMAIN"
echo "   Cloud Service: $CLOUD_SERVICE"
echo "   Landing Service: $LANDING_SERVICE"
echo ""

# Validate prerequisites
print_step "🔍 Checking prerequisites..."

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
    print_error "gcloud CLI is not installed"
    echo "Visit: https://cloud.google.com/sdk/docs/install"
    exit 1
fi
print_success "gcloud CLI found"

# Check if authenticated
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" | grep -q "@"; then
    print_error "Not authenticated with gcloud"
    echo "Run: gcloud auth login"
    exit 1
fi
print_success "gcloud authentication verified"

# Set the project
print_step "📋 Setting project: $PROJECT_ID"
gcloud config set project $PROJECT_ID

# Enable required APIs
print_step "🔧 Enabling required Google Cloud APIs..."
gcloud services enable run.googleapis.com --quiet
gcloud services enable cloudbuild.googleapis.com --quiet
gcloud services enable artifactregistry.googleapis.com --quiet
print_success "All required APIs enabled"

# Function to deploy backend
deploy_backend() {
    print_step "🚀 Deploying Backend Service ($CLOUD_SERVICE)..."
    
    # Update production environment file
    print_step "📝 Updating backend production configuration..."
    cat > cloud/.env.production << EOFILE
# KELEDON Cloud - Production Environment for Cloud Run
# Auto-generated by deploy-all.sh on $(date)

# Server Configuration
PORT=8080
NODE_ENV=production

# CORS Configuration (comma-separated list of allowed origins)
CORS_ORIGINS=chrome-extension://*,${DOMAIN:+https://$DOMAIN}

# Supabase Database Configuration (KELEDON Production)
SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY

# Default Providers (configured via management UI in production)
DEFAULT_STT_PROVIDER=mock
DEFAULT_TTS_PROVIDER=mock

# NOTE: API keys for STT/TTS/LLM providers should be configured
# through the management UI at /admin/providers after deployment
EOFILE
    
    # Deploy backend
    gcloud run deploy $CLOUD_SERVICE \
        --source cloud \
        --region $REGION \
        --allow-unauthenticated \
        --cpu 1 \
        --memory 1Gi \
        --max-instances 10 \
        --min-instances 0 \
        --timeout 300 \
        --concurrency 80 \
        --set-env-vars "$(cat cloud/.env.production | grep -v '^#' | tr '\n' ',' | sed 's/,$//')" \
        --quiet
    
    # Get backend URL
    CLOUD_URL=$(gcloud run services describe $CLOUD_SERVICE \
        --region $REGION \
        --format 'value(status.url)')
    
    print_success "Backend deployed successfully"
    echo "   🌐 Backend URL: $CLOUD_URL"
    echo "   🔗 Health Check: $CLOUD_URL/health"
}

# Function to deploy frontend
deploy_frontend() {
    print_step "🚀 Deploying Frontend Service ($LANDING_SERVICE)..."
    
    # Update frontend environment file with backend URL
    print_step "📝 Updating frontend production configuration..."
    cat > landing/.env.production << EOFILE
# KELEDON Landing - Production Environment for Cloud Run
# Auto-generated by deploy-all.sh on $(date)

# Frontend Configuration
VITE_NODE_ENV=production

# Supabase Configuration (same as cloud service)
VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

# Backend API URL (Cloud Run service URL)
VITE_API_URL=$CLOUD_URL

# WebSocket URL (same as backend API URL with WebSocket protocol)
VITE_WEBSOCKET_URL=wss://$(echo $CLOUD_URL | sed 's|https://||')

# Application Configuration
VITE_APP_NAME=KELEDON
VITE_APP_VERSION=1.0.0
EOFILE
    
    # Deploy frontend
    gcloud run deploy $LANDING_SERVICE \
        --source landing \
        --region $REGION \
        --allow-unauthenticated \
        --cpu 1 \
        --memory 512Mi \
        --max-instances 10 \
        --min-instances 0 \
        --timeout 60 \
        --concurrency 100 \
        --quiet
    
    # Get frontend URL
    LANDING_URL=$(gcloud run services describe $LANDING_SERVICE \
        --region $REGION \
        --format 'value(status.url)')
    
    print_success "Frontend deployed successfully"
    echo "   🌐 Frontend URL: $LANDING_URL"
}

# Function to test deployments
test_deployments() {
    print_step "🧪 Testing deployed services..."
    
    # Test backend health
    if curl -f -s "$CLOUD_URL/health" > /dev/null; then
        print_success "Backend health check passed"
    else
        print_warning "Backend health check failed (may still be starting)"
    fi
    
    # Test frontend accessibility
    if curl -f -s "$LANDING_URL" > /dev/null; then
        print_success "Frontend is accessible"
    else
        print_warning "Frontend accessibility test failed (may still be starting)"
    fi
}

# Function to setup custom domain (optional)
setup_custom_domain() {
    if [[ -n "$DOMAIN" ]]; then
        print_step "🌐 Setting up custom domain: $DOMAIN"
        
        # Map domain to frontend
        echo "To map $DOMAIN to your frontend, run:"
        echo "gcloud run domain mappings create $DOMAIN \\"
        echo "  --region=$REGION \\"
        echo "  --service=$LANDING_SERVICE"
        
        # Note: Domain mapping for backend is optional and usually not needed
        print_warning "Note: DNS configuration must be done manually"
    fi
}

# Function to generate cloudconf.md
generate_cloudconf() {
    print_step "📄 Generating deployment documentation..."
    
    cat > cloudconf.md << EOFILE
# KELEDON Cloud Run Deployment Configuration

**Deployment Date**: $(date)
**Project ID**: $PROJECT_ID
**Region**: $REGION
**Domain**: ${DOMAIN:-"Not configured"}

## 🌐 Service URLs

### Backend Service
- **Service Name**: $CLOUD_SERVICE
- **URL**: $CLOUD_URL
- **Health Check**: $CLOUD_URL/health
- **WebSocket**: wss://$(echo $CLOUD_URL | sed 's|https://||')

### Frontend Service
- **Service Name**: $LANDING_SERVICE
- **URL**: $LANDING_URL
- **Custom Domain**: ${DOMAIN:-"Not configured"}

## 🔧 Configuration

### Supabase Database
- **URL**: $SUPABASE_URL
- **Status**: ✅ Configured (KELEDON Production)

### CORS Configuration
- **Backend Origins**: chrome-extension://*, ${DOMAIN:+https://$DOMAIN}

## 📋 Post-Deployment Checklist

### 1. Verify Services
- [ ] Backend health: \`curl $CLOUD_URL/health\`
- [ ] Frontend accessible: Visit $LANDING_URL
- [ ] Chrome extension can connect

### 2. Configure Provider Keys
Visit: $CLOUD_URL/admin/providers
- [ ] Deepgram API Key (STT)
- [ ] ElevenLabs API Key (TTS)
- [ ] OpenAI API Key (LLM)

### 3. Chrome Extension Configuration
Update extension manifest or settings:
- **Backend URL**: $CLOUD_URL
- **WebSocket URL**: wss://$(echo $CLOUD_URL | sed 's|https://||')

### 4. Optional: Custom Domain
If you specified a domain, complete DNS setup:
1. Run domain mapping command (shown above)
2. Configure DNS records as instructed by gcloud
3
